import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavigationBar } from "@/components/ui/nav-bar/navigation-menu";
import { ThemeProvider } from "@/components/theme"
import {Toaster } from "@/components/ui/toaster"
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import './globals.css'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<ClerkProvider
    appearance={{
        variables: {
            colorPrimary: 'hsl(263.4, 70%, 50.4%)', // change this value (you can get it from you're css variables, make sure to include 'hsl' and commas)
                },
            }}
>
...
</ClerkProvider>

export default function RootLayout({children,}: 
  Readonly<{children: React.ReactNode;}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
            <NavigationBar/>
            {/* <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn> */}
          {children}
          <Toaster/>
          </ThemeProvider>
      </body>
    </html>
  </ClerkProvider>
    );
  }
  
  // export default function RootLayout({
  //   children,
  // }: {
  //   children: React.ReactNode
  // }) {
  //   return (
  //       <html lang="en">
  //         <body>
  //           {children}
  //         </body>
  //       </html>
  //   )
  // }